permalink: pretty
markdown: kramdown

title: Lightning Store Tracker
author: Joel Ross
description:
    A list of stores using Lightning and/or Bitcoin as a payment method.
url: https://www.lightningtracker.io
repo: https://github.com/jrosco/lightningtracker
img: img/logo.png
twitter: lightningtrackr
sass:
    style: compressed

exclude:
    - CNAME
    - CONTRIBUTING.md
    - EXCLUSION.md
    - Gemfile
    - LICENSE
    - README.md
    - Rakefile
    - verify.rb
    - vendor
    - websites_schema.yml

theme: jekyll-theme-cayman
